// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.15.3
// source: proto/daemon/v1/daemon.proto

package daemon

import (
	context "context"
	colibri "github.com/scionproto/scion/go/pkg/proto/colibri"
	drkey "github.com/scionproto/scion/go/pkg/proto/drkey"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LinkType int32

const (
	LinkType_LINK_TYPE_UNSPECIFIED LinkType = 0
	LinkType_LINK_TYPE_DIRECT      LinkType = 1
	LinkType_LINK_TYPE_MULTI_HOP   LinkType = 2
	LinkType_LINK_TYPE_OPEN_NET    LinkType = 3
)

// Enum value maps for LinkType.
var (
	LinkType_name = map[int32]string{
		0: "LINK_TYPE_UNSPECIFIED",
		1: "LINK_TYPE_DIRECT",
		2: "LINK_TYPE_MULTI_HOP",
		3: "LINK_TYPE_OPEN_NET",
	}
	LinkType_value = map[string]int32{
		"LINK_TYPE_UNSPECIFIED": 0,
		"LINK_TYPE_DIRECT":      1,
		"LINK_TYPE_MULTI_HOP":   2,
		"LINK_TYPE_OPEN_NET":    3,
	}
)

func (x LinkType) Enum() *LinkType {
	p := new(LinkType)
	*p = x
	return p
}

func (x LinkType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LinkType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_daemon_v1_daemon_proto_enumTypes[0].Descriptor()
}

func (LinkType) Type() protoreflect.EnumType {
	return &file_proto_daemon_v1_daemon_proto_enumTypes[0]
}

func (x LinkType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LinkType.Descriptor instead.
func (LinkType) EnumDescriptor() ([]byte, []int) {
	return file_proto_daemon_v1_daemon_proto_rawDescGZIP(), []int{0}
}

type PathsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SourceIsdAs      uint64 `protobuf:"varint,1,opt,name=source_isd_as,json=sourceIsdAs,proto3" json:"source_isd_as,omitempty"`
	DestinationIsdAs uint64 `protobuf:"varint,2,opt,name=destination_isd_as,json=destinationIsdAs,proto3" json:"destination_isd_as,omitempty"`
	Refresh          bool   `protobuf:"varint,3,opt,name=refresh,proto3" json:"refresh,omitempty"`
	Hidden           bool   `protobuf:"varint,4,opt,name=hidden,proto3" json:"hidden,omitempty"`
}

func (x *PathsRequest) Reset() {
	*x = PathsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_daemon_v1_daemon_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PathsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathsRequest) ProtoMessage() {}

func (x *PathsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_daemon_v1_daemon_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathsRequest.ProtoReflect.Descriptor instead.
func (*PathsRequest) Descriptor() ([]byte, []int) {
	return file_proto_daemon_v1_daemon_proto_rawDescGZIP(), []int{0}
}

func (x *PathsRequest) GetSourceIsdAs() uint64 {
	if x != nil {
		return x.SourceIsdAs
	}
	return 0
}

func (x *PathsRequest) GetDestinationIsdAs() uint64 {
	if x != nil {
		return x.DestinationIsdAs
	}
	return 0
}

func (x *PathsRequest) GetRefresh() bool {
	if x != nil {
		return x.Refresh
	}
	return false
}

func (x *PathsRequest) GetHidden() bool {
	if x != nil {
		return x.Hidden
	}
	return false
}

type PathsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Paths []*Path `protobuf:"bytes,1,rep,name=paths,proto3" json:"paths,omitempty"`
}

func (x *PathsResponse) Reset() {
	*x = PathsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_daemon_v1_daemon_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PathsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathsResponse) ProtoMessage() {}

func (x *PathsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_daemon_v1_daemon_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathsResponse.ProtoReflect.Descriptor instead.
func (*PathsResponse) Descriptor() ([]byte, []int) {
	return file_proto_daemon_v1_daemon_proto_rawDescGZIP(), []int{1}
}

func (x *PathsResponse) GetPaths() []*Path {
	if x != nil {
		return x.Paths
	}
	return nil
}

type Path struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Raw          []byte                 `protobuf:"bytes,1,opt,name=raw,proto3" json:"raw,omitempty"`
	Interface    *Interface             `protobuf:"bytes,2,opt,name=interface,proto3" json:"interface,omitempty"`
	Interfaces   []*PathInterface       `protobuf:"bytes,3,rep,name=interfaces,proto3" json:"interfaces,omitempty"`
	Mtu          uint32                 `protobuf:"varint,4,opt,name=mtu,proto3" json:"mtu,omitempty"`
	Expiration   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=expiration,proto3" json:"expiration,omitempty"`
	Latency      []*durationpb.Duration `protobuf:"bytes,6,rep,name=latency,proto3" json:"latency,omitempty"`
	Bandwidth    []uint64               `protobuf:"varint,7,rep,packed,name=bandwidth,proto3" json:"bandwidth,omitempty"`
	Geo          []*GeoCoordinates      `protobuf:"bytes,8,rep,name=geo,proto3" json:"geo,omitempty"`
	LinkType     []LinkType             `protobuf:"varint,9,rep,packed,name=link_type,json=linkType,proto3,enum=proto.daemon.v1.LinkType" json:"link_type,omitempty"`
	InternalHops []uint32               `protobuf:"varint,10,rep,packed,name=internal_hops,json=internalHops,proto3" json:"internal_hops,omitempty"`
	Notes        []string               `protobuf:"bytes,11,rep,name=notes,proto3" json:"notes,omitempty"`
}

func (x *Path) Reset() {
	*x = Path{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_daemon_v1_daemon_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Path) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Path) ProtoMessage() {}

func (x *Path) ProtoReflect() protoreflect.Message {
	mi := &file_proto_daemon_v1_daemon_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Path.ProtoReflect.Descriptor instead.
func (*Path) Descriptor() ([]byte, []int) {
	return file_proto_daemon_v1_daemon_proto_rawDescGZIP(), []int{2}
}

func (x *Path) GetRaw() []byte {
	if x != nil {
		return x.Raw
	}
	return nil
}

func (x *Path) GetInterface() *Interface {
	if x != nil {
		return x.Interface
	}
	return nil
}

func (x *Path) GetInterfaces() []*PathInterface {
	if x != nil {
		return x.Interfaces
	}
	return nil
}

func (x *Path) GetMtu() uint32 {
	if x != nil {
		return x.Mtu
	}
	return 0
}

func (x *Path) GetExpiration() *timestamppb.Timestamp {
	if x != nil {
		return x.Expiration
	}
	return nil
}

func (x *Path) GetLatency() []*durationpb.Duration {
	if x != nil {
		return x.Latency
	}
	return nil
}

func (x *Path) GetBandwidth() []uint64 {
	if x != nil {
		return x.Bandwidth
	}
	return nil
}

func (x *Path) GetGeo() []*GeoCoordinates {
	if x != nil {
		return x.Geo
	}
	return nil
}

func (x *Path) GetLinkType() []LinkType {
	if x != nil {
		return x.LinkType
	}
	return nil
}

func (x *Path) GetInternalHops() []uint32 {
	if x != nil {
		return x.InternalHops
	}
	return nil
}

func (x *Path) GetNotes() []string {
	if x != nil {
		return x.Notes
	}
	return nil
}

type PathInterface struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsdAs uint64 `protobuf:"varint,1,opt,name=isd_as,json=isdAs,proto3" json:"isd_as,omitempty"`
	Id    uint64 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *PathInterface) Reset() {
	*x = PathInterface{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_daemon_v1_daemon_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PathInterface) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathInterface) ProtoMessage() {}

func (x *PathInterface) ProtoReflect() protoreflect.Message {
	mi := &file_proto_daemon_v1_daemon_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathInterface.ProtoReflect.Descriptor instead.
func (*PathInterface) Descriptor() ([]byte, []int) {
	return file_proto_daemon_v1_daemon_proto_rawDescGZIP(), []int{3}
}

func (x *PathInterface) GetIsdAs() uint64 {
	if x != nil {
		return x.IsdAs
	}
	return 0
}

func (x *PathInterface) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GeoCoordinates struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Latitude  float32 `protobuf:"fixed32,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude float32 `protobuf:"fixed32,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Address   string  `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *GeoCoordinates) Reset() {
	*x = GeoCoordinates{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_daemon_v1_daemon_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GeoCoordinates) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeoCoordinates) ProtoMessage() {}

func (x *GeoCoordinates) ProtoReflect() protoreflect.Message {
	mi := &file_proto_daemon_v1_daemon_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeoCoordinates.ProtoReflect.Descriptor instead.
func (*GeoCoordinates) Descriptor() ([]byte, []int) {
	return file_proto_daemon_v1_daemon_proto_rawDescGZIP(), []int{4}
}

func (x *GeoCoordinates) GetLatitude() float32 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *GeoCoordinates) GetLongitude() float32 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *GeoCoordinates) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type ASRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsdAs uint64 `protobuf:"varint,1,opt,name=isd_as,json=isdAs,proto3" json:"isd_as,omitempty"`
}

func (x *ASRequest) Reset() {
	*x = ASRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_daemon_v1_daemon_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ASRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ASRequest) ProtoMessage() {}

func (x *ASRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_daemon_v1_daemon_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ASRequest.ProtoReflect.Descriptor instead.
func (*ASRequest) Descriptor() ([]byte, []int) {
	return file_proto_daemon_v1_daemon_proto_rawDescGZIP(), []int{5}
}

func (x *ASRequest) GetIsdAs() uint64 {
	if x != nil {
		return x.IsdAs
	}
	return 0
}

type ASResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsdAs uint64 `protobuf:"varint,1,opt,name=isd_as,json=isdAs,proto3" json:"isd_as,omitempty"`
	Core  bool   `protobuf:"varint,2,opt,name=core,proto3" json:"core,omitempty"`
	Mtu   uint32 `protobuf:"varint,3,opt,name=mtu,proto3" json:"mtu,omitempty"`
}

func (x *ASResponse) Reset() {
	*x = ASResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_daemon_v1_daemon_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ASResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ASResponse) ProtoMessage() {}

func (x *ASResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_daemon_v1_daemon_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ASResponse.ProtoReflect.Descriptor instead.
func (*ASResponse) Descriptor() ([]byte, []int) {
	return file_proto_daemon_v1_daemon_proto_rawDescGZIP(), []int{6}
}

func (x *ASResponse) GetIsdAs() uint64 {
	if x != nil {
		return x.IsdAs
	}
	return 0
}

func (x *ASResponse) GetCore() bool {
	if x != nil {
		return x.Core
	}
	return false
}

func (x *ASResponse) GetMtu() uint32 {
	if x != nil {
		return x.Mtu
	}
	return 0
}

type InterfacesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *InterfacesRequest) Reset() {
	*x = InterfacesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_daemon_v1_daemon_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InterfacesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterfacesRequest) ProtoMessage() {}

func (x *InterfacesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_daemon_v1_daemon_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterfacesRequest.ProtoReflect.Descriptor instead.
func (*InterfacesRequest) Descriptor() ([]byte, []int) {
	return file_proto_daemon_v1_daemon_proto_rawDescGZIP(), []int{7}
}

type InterfacesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Interfaces map[uint64]*Interface `protobuf:"bytes,1,rep,name=interfaces,proto3" json:"interfaces,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *InterfacesResponse) Reset() {
	*x = InterfacesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_daemon_v1_daemon_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InterfacesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterfacesResponse) ProtoMessage() {}

func (x *InterfacesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_daemon_v1_daemon_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterfacesResponse.ProtoReflect.Descriptor instead.
func (*InterfacesResponse) Descriptor() ([]byte, []int) {
	return file_proto_daemon_v1_daemon_proto_rawDescGZIP(), []int{8}
}

func (x *InterfacesResponse) GetInterfaces() map[uint64]*Interface {
	if x != nil {
		return x.Interfaces
	}
	return nil
}

type Interface struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address *Underlay `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *Interface) Reset() {
	*x = Interface{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_daemon_v1_daemon_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Interface) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Interface) ProtoMessage() {}

func (x *Interface) ProtoReflect() protoreflect.Message {
	mi := &file_proto_daemon_v1_daemon_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Interface.ProtoReflect.Descriptor instead.
func (*Interface) Descriptor() ([]byte, []int) {
	return file_proto_daemon_v1_daemon_proto_rawDescGZIP(), []int{9}
}

func (x *Interface) GetAddress() *Underlay {
	if x != nil {
		return x.Address
	}
	return nil
}

type ServicesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ServicesRequest) Reset() {
	*x = ServicesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_daemon_v1_daemon_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServicesRequest) ProtoMessage() {}

func (x *ServicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_daemon_v1_daemon_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServicesRequest.ProtoReflect.Descriptor instead.
func (*ServicesRequest) Descriptor() ([]byte, []int) {
	return file_proto_daemon_v1_daemon_proto_rawDescGZIP(), []int{10}
}

type ServicesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Services map[string]*ListService `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *ServicesResponse) Reset() {
	*x = ServicesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_daemon_v1_daemon_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServicesResponse) ProtoMessage() {}

func (x *ServicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_daemon_v1_daemon_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServicesResponse.ProtoReflect.Descriptor instead.
func (*ServicesResponse) Descriptor() ([]byte, []int) {
	return file_proto_daemon_v1_daemon_proto_rawDescGZIP(), []int{11}
}

func (x *ServicesResponse) GetServices() map[string]*ListService {
	if x != nil {
		return x.Services
	}
	return nil
}

type ListService struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Services []*Service `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
}

func (x *ListService) Reset() {
	*x = ListService{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_daemon_v1_daemon_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListService) ProtoMessage() {}

func (x *ListService) ProtoReflect() protoreflect.Message {
	mi := &file_proto_daemon_v1_daemon_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListService.ProtoReflect.Descriptor instead.
func (*ListService) Descriptor() ([]byte, []int) {
	return file_proto_daemon_v1_daemon_proto_rawDescGZIP(), []int{12}
}

func (x *ListService) GetServices() []*Service {
	if x != nil {
		return x.Services
	}
	return nil
}

type Service struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uri string `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
}

func (x *Service) Reset() {
	*x = Service{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_daemon_v1_daemon_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service) ProtoMessage() {}

func (x *Service) ProtoReflect() protoreflect.Message {
	mi := &file_proto_daemon_v1_daemon_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Service.ProtoReflect.Descriptor instead.
func (*Service) Descriptor() ([]byte, []int) {
	return file_proto_daemon_v1_daemon_proto_rawDescGZIP(), []int{13}
}

func (x *Service) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

type Underlay struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *Underlay) Reset() {
	*x = Underlay{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_daemon_v1_daemon_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Underlay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Underlay) ProtoMessage() {}

func (x *Underlay) ProtoReflect() protoreflect.Message {
	mi := &file_proto_daemon_v1_daemon_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Underlay.ProtoReflect.Descriptor instead.
func (*Underlay) Descriptor() ([]byte, []int) {
	return file_proto_daemon_v1_daemon_proto_rawDescGZIP(), []int{14}
}

func (x *Underlay) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type NotifyInterfaceDownRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsdAs uint64 `protobuf:"varint,1,opt,name=isd_as,json=isdAs,proto3" json:"isd_as,omitempty"`
	Id    uint64 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *NotifyInterfaceDownRequest) Reset() {
	*x = NotifyInterfaceDownRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_daemon_v1_daemon_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotifyInterfaceDownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyInterfaceDownRequest) ProtoMessage() {}

func (x *NotifyInterfaceDownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_daemon_v1_daemon_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyInterfaceDownRequest.ProtoReflect.Descriptor instead.
func (*NotifyInterfaceDownRequest) Descriptor() ([]byte, []int) {
	return file_proto_daemon_v1_daemon_proto_rawDescGZIP(), []int{15}
}

func (x *NotifyInterfaceDownRequest) GetIsdAs() uint64 {
	if x != nil {
		return x.IsdAs
	}
	return 0
}

func (x *NotifyInterfaceDownRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type NotifyInterfaceDownResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NotifyInterfaceDownResponse) Reset() {
	*x = NotifyInterfaceDownResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_daemon_v1_daemon_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotifyInterfaceDownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyInterfaceDownResponse) ProtoMessage() {}

func (x *NotifyInterfaceDownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_daemon_v1_daemon_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyInterfaceDownResponse.ProtoReflect.Descriptor instead.
func (*NotifyInterfaceDownResponse) Descriptor() ([]byte, []int) {
	return file_proto_daemon_v1_daemon_proto_rawDescGZIP(), []int{16}
}

type DRKeyLvl2Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BaseReq *drkey.DRKeyLvl2Request `protobuf:"bytes,1,opt,name=base_req,json=baseReq,proto3" json:"base_req,omitempty"`
}

func (x *DRKeyLvl2Request) Reset() {
	*x = DRKeyLvl2Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_daemon_v1_daemon_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DRKeyLvl2Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DRKeyLvl2Request) ProtoMessage() {}

func (x *DRKeyLvl2Request) ProtoReflect() protoreflect.Message {
	mi := &file_proto_daemon_v1_daemon_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DRKeyLvl2Request.ProtoReflect.Descriptor instead.
func (*DRKeyLvl2Request) Descriptor() ([]byte, []int) {
	return file_proto_daemon_v1_daemon_proto_rawDescGZIP(), []int{17}
}

func (x *DRKeyLvl2Request) GetBaseReq() *drkey.DRKeyLvl2Request {
	if x != nil {
		return x.BaseReq
	}
	return nil
}

type DRKeyLvl2Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BaseRep *drkey.DRKeyLvl2Response `protobuf:"bytes,1,opt,name=base_rep,json=baseRep,proto3" json:"base_rep,omitempty"`
}

func (x *DRKeyLvl2Response) Reset() {
	*x = DRKeyLvl2Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_daemon_v1_daemon_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DRKeyLvl2Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DRKeyLvl2Response) ProtoMessage() {}

func (x *DRKeyLvl2Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_daemon_v1_daemon_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DRKeyLvl2Response.ProtoReflect.Descriptor instead.
func (*DRKeyLvl2Response) Descriptor() ([]byte, []int) {
	return file_proto_daemon_v1_daemon_proto_rawDescGZIP(), []int{18}
}

func (x *DRKeyLvl2Response) GetBaseRep() *drkey.DRKeyLvl2Response {
	if x != nil {
		return x.BaseRep
	}
	return nil
}

type ColibriListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Base *colibri.ListStitchablesRequest `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
}

func (x *ColibriListRequest) Reset() {
	*x = ColibriListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_daemon_v1_daemon_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ColibriListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColibriListRequest) ProtoMessage() {}

func (x *ColibriListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_daemon_v1_daemon_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColibriListRequest.ProtoReflect.Descriptor instead.
func (*ColibriListRequest) Descriptor() ([]byte, []int) {
	return file_proto_daemon_v1_daemon_proto_rawDescGZIP(), []int{19}
}

func (x *ColibriListRequest) GetBase() *colibri.ListStitchablesRequest {
	if x != nil {
		return x.Base
	}
	return nil
}

type ColibriListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Base *colibri.ListStitchablesResponse `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
}

func (x *ColibriListResponse) Reset() {
	*x = ColibriListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_daemon_v1_daemon_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ColibriListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColibriListResponse) ProtoMessage() {}

func (x *ColibriListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_daemon_v1_daemon_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColibriListResponse.ProtoReflect.Descriptor instead.
func (*ColibriListResponse) Descriptor() ([]byte, []int) {
	return file_proto_daemon_v1_daemon_proto_rawDescGZIP(), []int{20}
}

func (x *ColibriListResponse) GetBase() *colibri.ListStitchablesResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

type ColibriSetupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Base *colibri.DaemonSetupRequest `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
}

func (x *ColibriSetupRequest) Reset() {
	*x = ColibriSetupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_daemon_v1_daemon_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ColibriSetupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColibriSetupRequest) ProtoMessage() {}

func (x *ColibriSetupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_daemon_v1_daemon_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColibriSetupRequest.ProtoReflect.Descriptor instead.
func (*ColibriSetupRequest) Descriptor() ([]byte, []int) {
	return file_proto_daemon_v1_daemon_proto_rawDescGZIP(), []int{21}
}

func (x *ColibriSetupRequest) GetBase() *colibri.DaemonSetupRequest {
	if x != nil {
		return x.Base
	}
	return nil
}

type ColibriSetupResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Base *colibri.DaemonSetupResponse `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
}

func (x *ColibriSetupResponse) Reset() {
	*x = ColibriSetupResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_daemon_v1_daemon_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ColibriSetupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColibriSetupResponse) ProtoMessage() {}

func (x *ColibriSetupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_daemon_v1_daemon_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColibriSetupResponse.ProtoReflect.Descriptor instead.
func (*ColibriSetupResponse) Descriptor() ([]byte, []int) {
	return file_proto_daemon_v1_daemon_proto_rawDescGZIP(), []int{22}
}

func (x *ColibriSetupResponse) GetBase() *colibri.DaemonSetupResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

type ColibriCleanupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Base *colibri.DaemonCleanupRequest `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
}

func (x *ColibriCleanupRequest) Reset() {
	*x = ColibriCleanupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_daemon_v1_daemon_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ColibriCleanupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColibriCleanupRequest) ProtoMessage() {}

func (x *ColibriCleanupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_daemon_v1_daemon_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColibriCleanupRequest.ProtoReflect.Descriptor instead.
func (*ColibriCleanupRequest) Descriptor() ([]byte, []int) {
	return file_proto_daemon_v1_daemon_proto_rawDescGZIP(), []int{23}
}

func (x *ColibriCleanupRequest) GetBase() *colibri.DaemonCleanupRequest {
	if x != nil {
		return x.Base
	}
	return nil
}

type ColibriCleanupResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Base *colibri.DaemonCleanupResponse `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
}

func (x *ColibriCleanupResponse) Reset() {
	*x = ColibriCleanupResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_daemon_v1_daemon_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ColibriCleanupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColibriCleanupResponse) ProtoMessage() {}

func (x *ColibriCleanupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_daemon_v1_daemon_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColibriCleanupResponse.ProtoReflect.Descriptor instead.
func (*ColibriCleanupResponse) Descriptor() ([]byte, []int) {
	return file_proto_daemon_v1_daemon_proto_rawDescGZIP(), []int{24}
}

func (x *ColibriCleanupResponse) GetBase() *colibri.DaemonCleanupResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

type ColibriAdmissionEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Base *colibri.DaemonAdmissionEntry `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
}

func (x *ColibriAdmissionEntry) Reset() {
	*x = ColibriAdmissionEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_daemon_v1_daemon_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ColibriAdmissionEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColibriAdmissionEntry) ProtoMessage() {}

func (x *ColibriAdmissionEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_daemon_v1_daemon_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColibriAdmissionEntry.ProtoReflect.Descriptor instead.
func (*ColibriAdmissionEntry) Descriptor() ([]byte, []int) {
	return file_proto_daemon_v1_daemon_proto_rawDescGZIP(), []int{25}
}

func (x *ColibriAdmissionEntry) GetBase() *colibri.DaemonAdmissionEntry {
	if x != nil {
		return x.Base
	}
	return nil
}

type ColibriAdmissionEntryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Base *colibri.DaemonAdmissionEntryResponse `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
}

func (x *ColibriAdmissionEntryResponse) Reset() {
	*x = ColibriAdmissionEntryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_daemon_v1_daemon_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ColibriAdmissionEntryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColibriAdmissionEntryResponse) ProtoMessage() {}

func (x *ColibriAdmissionEntryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_daemon_v1_daemon_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColibriAdmissionEntryResponse.ProtoReflect.Descriptor instead.
func (*ColibriAdmissionEntryResponse) Descriptor() ([]byte, []int) {
	return file_proto_daemon_v1_daemon_proto_rawDescGZIP(), []int{26}
}

func (x *ColibriAdmissionEntryResponse) GetBase() *colibri.DaemonAdmissionEntryResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

var File_proto_daemon_v1_daemon_proto protoreflect.FileDescriptor

var file_proto_daemon_v1_daemon_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x2f, 0x76,
	0x31, 0x2f, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x1a,
	0x1e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x72, 0x6b, 0x65, 0x79, 0x2f, 0x6d, 0x67, 0x6d,
	0x74, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x67, 0x6d, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x1e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6c, 0x69, 0x62, 0x72, 0x69, 0x2f, 0x76,
	0x31, 0x2f, 0x63, 0x6f, 0x6c, 0x69, 0x62, 0x72, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x92, 0x01, 0x0a, 0x0c, 0x50, 0x61, 0x74, 0x68, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x22, 0x0a, 0x0d, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x69, 0x73, 0x64, 0x5f,
	0x61, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x49, 0x73, 0x64, 0x41, 0x73, 0x12, 0x2c, 0x0a, 0x12, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x73, 0x64, 0x5f, 0x61, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x10, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x73,
	0x64, 0x41, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x12, 0x16, 0x0a,
	0x06, 0x68, 0x69, 0x64, 0x64, 0x65, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x68,
	0x69, 0x64, 0x64, 0x65, 0x6e, 0x22, 0x3c, 0x0a, 0x0d, 0x50, 0x61, 0x74, 0x68, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x05, 0x70, 0x61, 0x74, 0x68, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x64, 0x61,
	0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x61, 0x74, 0x68, 0x52, 0x05, 0x70, 0x61,
	0x74, 0x68, 0x73, 0x22, 0xd9, 0x03, 0x0a, 0x04, 0x50, 0x61, 0x74, 0x68, 0x12, 0x10, 0x0a, 0x03,
	0x72, 0x61, 0x77, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x72, 0x61, 0x77, 0x12, 0x38,
	0x0a, 0x09, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e,
	0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x52, 0x09, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x12, 0x3e, 0x0a, 0x0a, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x66, 0x61, 0x63, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x50,
	0x61, 0x74, 0x68, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x52, 0x0a, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x74, 0x75, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x6d, 0x74, 0x75, 0x12, 0x3a, 0x0a, 0x0a, 0x65, 0x78,
	0x70, 0x69, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a, 0x65, 0x78, 0x70, 0x69,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x33, 0x0a, 0x07, 0x6c, 0x61, 0x74, 0x65, 0x6e, 0x63,
	0x79, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x07, 0x6c, 0x61, 0x74, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x62,
	0x61, 0x6e, 0x64, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x07, 0x20, 0x03, 0x28, 0x04, 0x52, 0x09,
	0x62, 0x61, 0x6e, 0x64, 0x77, 0x69, 0x64, 0x74, 0x68, 0x12, 0x31, 0x0a, 0x03, 0x67, 0x65, 0x6f,
	0x18, 0x08, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x64,
	0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x6f, 0x43, 0x6f, 0x6f, 0x72,
	0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x73, 0x52, 0x03, 0x67, 0x65, 0x6f, 0x12, 0x36, 0x0a, 0x09,
	0x6c, 0x69, 0x6e, 0x6b, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x09, 0x20, 0x03, 0x28, 0x0e, 0x32,
	0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x76,
	0x31, 0x2e, 0x4c, 0x69, 0x6e, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x6c, 0x69, 0x6e, 0x6b,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x5f, 0x68, 0x6f, 0x70, 0x73, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x0c, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x6e, 0x61, 0x6c, 0x48, 0x6f, 0x70, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x6f, 0x74,
	0x65, 0x73, 0x18, 0x0b, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x6e, 0x6f, 0x74, 0x65, 0x73, 0x22,
	0x36, 0x0a, 0x0d, 0x50, 0x61, 0x74, 0x68, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65,
	0x12, 0x15, 0x0a, 0x06, 0x69, 0x73, 0x64, 0x5f, 0x61, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x05, 0x69, 0x73, 0x64, 0x41, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x22, 0x64, 0x0a, 0x0e, 0x47, 0x65, 0x6f, 0x43, 0x6f,
	0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x74,
	0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x6c, 0x61, 0x74,
	0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75,
	0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74,
	0x75, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x22, 0x0a,
	0x09, 0x41, 0x53, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x69, 0x73,
	0x64, 0x5f, 0x61, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x69, 0x73, 0x64, 0x41,
	0x73, 0x22, 0x49, 0x0a, 0x0a, 0x41, 0x53, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x15, 0x0a, 0x06, 0x69, 0x73, 0x64, 0x5f, 0x61, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x05, 0x69, 0x73, 0x64, 0x41, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x74,
	0x75, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x6d, 0x74, 0x75, 0x22, 0x13, 0x0a, 0x11,
	0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0xc4, 0x01, 0x0a, 0x12, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x53, 0x0a, 0x0a, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x66, 0x61, 0x63, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x33, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x49,
	0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x52, 0x0a, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x73, 0x1a, 0x59, 0x0a,
	0x0f, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x30, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e,
	0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x40, 0x0a, 0x09, 0x49, 0x6e, 0x74, 0x65,
	0x72, 0x66, 0x61, 0x63, 0x65, 0x12, 0x33, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x64,
	0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x6e, 0x64, 0x65, 0x72, 0x6c, 0x61,
	0x79, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x11, 0x0a, 0x0f, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0xba, 0x01,
	0x0a, 0x10, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x4b, 0x0a, 0x08, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x64, 0x61, 0x65,
	0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x1a,
	0x59, 0x0a, 0x0d, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x32, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e,
	0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x43, 0x0a, 0x0b, 0x4c, 0x69,
	0x73, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x34, 0x0a, 0x08, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x22,
	0x1b, 0x0a, 0x07, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72,
	0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x69, 0x22, 0x24, 0x0a, 0x08,
	0x55, 0x6e, 0x64, 0x65, 0x72, 0x6c, 0x61, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x22, 0x43, 0x0a, 0x1a, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x49, 0x6e, 0x74, 0x65,
	0x72, 0x66, 0x61, 0x63, 0x65, 0x44, 0x6f, 0x77, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x15, 0x0a, 0x06, 0x69, 0x73, 0x64, 0x5f, 0x61, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x05, 0x69, 0x73, 0x64, 0x41, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x22, 0x1d, 0x0a, 0x1b, 0x4e, 0x6f, 0x74, 0x69, 0x66,
	0x79, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x44, 0x6f, 0x77, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x54, 0x0a, 0x10, 0x44, 0x52, 0x4b, 0x65, 0x79, 0x4c,
	0x76, 0x6c, 0x32, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x40, 0x0a, 0x08, 0x62, 0x61,
	0x73, 0x65, 0x5f, 0x72, 0x65, 0x71, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x64, 0x72, 0x6b, 0x65, 0x79, 0x2e, 0x6d, 0x67, 0x6d, 0x74, 0x2e,
	0x76, 0x31, 0x2e, 0x44, 0x52, 0x4b, 0x65, 0x79, 0x4c, 0x76, 0x6c, 0x32, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x52, 0x07, 0x62, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x22, 0x56, 0x0a, 0x11,
	0x44, 0x52, 0x4b, 0x65, 0x79, 0x4c, 0x76, 0x6c, 0x32, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x41, 0x0a, 0x08, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x72, 0x65, 0x70, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x64, 0x72, 0x6b, 0x65,
	0x79, 0x2e, 0x6d, 0x67, 0x6d, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x52, 0x4b, 0x65, 0x79, 0x4c,
	0x76, 0x6c, 0x32, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x07, 0x62, 0x61, 0x73,
	0x65, 0x52, 0x65, 0x70, 0x22, 0x52, 0x0a, 0x12, 0x43, 0x6f, 0x6c, 0x69, 0x62, 0x72, 0x69, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3c, 0x0a, 0x04, 0x62, 0x61,
	0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x63, 0x6f, 0x6c, 0x69, 0x62, 0x72, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x53, 0x74, 0x69, 0x74, 0x63, 0x68, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x52, 0x04, 0x62, 0x61, 0x73, 0x65, 0x22, 0x54, 0x0a, 0x13, 0x43, 0x6f, 0x6c, 0x69,
	0x62, 0x72, 0x69, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x3d, 0x0a, 0x04, 0x62, 0x61, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6c, 0x69, 0x62, 0x72, 0x69, 0x2e, 0x76, 0x31,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x74, 0x69, 0x74, 0x63, 0x68, 0x61, 0x62, 0x6c, 0x65, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x04, 0x62, 0x61, 0x73, 0x65, 0x22, 0x4f,
	0x0a, 0x13, 0x43, 0x6f, 0x6c, 0x69, 0x62, 0x72, 0x69, 0x53, 0x65, 0x74, 0x75, 0x70, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x38, 0x0a, 0x04, 0x62, 0x61, 0x73, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6c, 0x69,
	0x62, 0x72, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x53, 0x65, 0x74,
	0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x04, 0x62, 0x61, 0x73, 0x65, 0x22,
	0x51, 0x0a, 0x14, 0x43, 0x6f, 0x6c, 0x69, 0x62, 0x72, 0x69, 0x53, 0x65, 0x74, 0x75, 0x70, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x39, 0x0a, 0x04, 0x62, 0x61, 0x73, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f,
	0x6c, 0x69, 0x62, 0x72, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x53,
	0x65, 0x74, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x04, 0x62, 0x61,
	0x73, 0x65, 0x22, 0x53, 0x0a, 0x15, 0x43, 0x6f, 0x6c, 0x69, 0x62, 0x72, 0x69, 0x43, 0x6c, 0x65,
	0x61, 0x6e, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3a, 0x0a, 0x04, 0x62,
	0x61, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x63, 0x6f, 0x6c, 0x69, 0x62, 0x72, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x61, 0x65,
	0x6d, 0x6f, 0x6e, 0x43, 0x6c, 0x65, 0x61, 0x6e, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x52, 0x04, 0x62, 0x61, 0x73, 0x65, 0x22, 0x55, 0x0a, 0x16, 0x43, 0x6f, 0x6c, 0x69, 0x62,
	0x72, 0x69, 0x43, 0x6c, 0x65, 0x61, 0x6e, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x3b, 0x0a, 0x04, 0x62, 0x61, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x27, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6c, 0x69, 0x62, 0x72, 0x69, 0x2e,
	0x76, 0x31, 0x2e, 0x44, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x43, 0x6c, 0x65, 0x61, 0x6e, 0x75, 0x70,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x04, 0x62, 0x61, 0x73, 0x65, 0x22, 0x53,
	0x0a, 0x15, 0x43, 0x6f, 0x6c, 0x69, 0x62, 0x72, 0x69, 0x41, 0x64, 0x6d, 0x69, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x3a, 0x0a, 0x04, 0x62, 0x61, 0x73, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f,
	0x6c, 0x69, 0x62, 0x72, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x41,
	0x64, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x04, 0x62,
	0x61, 0x73, 0x65, 0x22, 0x63, 0x0a, 0x1d, 0x43, 0x6f, 0x6c, 0x69, 0x62, 0x72, 0x69, 0x41, 0x64,
	0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x42, 0x0a, 0x04, 0x62, 0x61, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6c, 0x69, 0x62,
	0x72, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x41, 0x64, 0x6d, 0x69,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x52, 0x04, 0x62, 0x61, 0x73, 0x65, 0x2a, 0x6c, 0x0a, 0x08, 0x4c, 0x69, 0x6e, 0x6b,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x19, 0x0a, 0x15, 0x4c, 0x49, 0x4e, 0x4b, 0x5f, 0x54, 0x59, 0x50,
	0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12,
	0x14, 0x0a, 0x10, 0x4c, 0x49, 0x4e, 0x4b, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x44, 0x49, 0x52,
	0x45, 0x43, 0x54, 0x10, 0x01, 0x12, 0x17, 0x0a, 0x13, 0x4c, 0x49, 0x4e, 0x4b, 0x5f, 0x54, 0x59,
	0x50, 0x45, 0x5f, 0x4d, 0x55, 0x4c, 0x54, 0x49, 0x5f, 0x48, 0x4f, 0x50, 0x10, 0x02, 0x12, 0x16,
	0x0a, 0x12, 0x4c, 0x49, 0x4e, 0x4b, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x4f, 0x50, 0x45, 0x4e,
	0x5f, 0x4e, 0x45, 0x54, 0x10, 0x03, 0x32, 0xb0, 0x07, 0x0a, 0x0d, 0x44, 0x61, 0x65, 0x6d, 0x6f,
	0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x48, 0x0a, 0x05, 0x50, 0x61, 0x74, 0x68,
	0x73, 0x12, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e,
	0x2e, 0x76, 0x31, 0x2e, 0x50, 0x61, 0x74, 0x68, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x2e,
	0x76, 0x31, 0x2e, 0x50, 0x61, 0x74, 0x68, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x3f, 0x0a, 0x02, 0x41, 0x53, 0x12, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x53, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x64, 0x61, 0x65,
	0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x53, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x57, 0x0a, 0x0a, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65,
	0x73, 0x12, 0x22, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e,
	0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x64, 0x61,
	0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63,
	0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x51, 0x0a, 0x08,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x12, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x72, 0x0a, 0x13, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61,
	0x63, 0x65, 0x44, 0x6f, 0x77, 0x6e, 0x12, 0x2b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x64,
	0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x49,
	0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x44, 0x6f, 0x77, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x2c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x64, 0x61, 0x65, 0x6d,
	0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x49, 0x6e, 0x74, 0x65,
	0x72, 0x66, 0x61, 0x63, 0x65, 0x44, 0x6f, 0x77, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x54, 0x0a, 0x09, 0x44, 0x52, 0x4b, 0x65, 0x79, 0x4c, 0x76, 0x6c, 0x32,
	0x12, 0x21, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x2e,
	0x76, 0x31, 0x2e, 0x44, 0x52, 0x4b, 0x65, 0x79, 0x4c, 0x76, 0x6c, 0x32, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x64, 0x61, 0x65, 0x6d,
	0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x52, 0x4b, 0x65, 0x79, 0x4c, 0x76, 0x6c, 0x32, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5e, 0x0a, 0x0f, 0x43, 0x6f, 0x6c,
	0x69, 0x62, 0x72, 0x69, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x73, 0x76, 0x73, 0x12, 0x23, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x43,
	0x6f, 0x6c, 0x69, 0x62, 0x72, 0x69, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x24, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e,
	0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6c, 0x69, 0x62, 0x72, 0x69, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x60, 0x0a, 0x0f, 0x43, 0x6f, 0x6c,
	0x69, 0x62, 0x72, 0x69, 0x53, 0x65, 0x74, 0x75, 0x70, 0x52, 0x73, 0x76, 0x12, 0x24, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x43,
	0x6f, 0x6c, 0x69, 0x62, 0x72, 0x69, 0x53, 0x65, 0x74, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x25, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x64, 0x61, 0x65, 0x6d, 0x6f,
	0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6c, 0x69, 0x62, 0x72, 0x69, 0x53, 0x65, 0x74, 0x75,
	0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x66, 0x0a, 0x11, 0x43,
	0x6f, 0x6c, 0x69, 0x62, 0x72, 0x69, 0x43, 0x6c, 0x65, 0x61, 0x6e, 0x75, 0x70, 0x52, 0x73, 0x76,
	0x12, 0x26, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x2e,
	0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6c, 0x69, 0x62, 0x72, 0x69, 0x43, 0x6c, 0x65, 0x61, 0x6e, 0x75,
	0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6c, 0x69, 0x62,
	0x72, 0x69, 0x43, 0x6c, 0x65, 0x61, 0x6e, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x74, 0x0a, 0x18, 0x43, 0x6f, 0x6c, 0x69, 0x62, 0x72, 0x69, 0x41, 0x64,
	0x64, 0x41, 0x64, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12,
	0x26, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x76,
	0x31, 0x2e, 0x43, 0x6f, 0x6c, 0x69, 0x62, 0x72, 0x69, 0x41, 0x64, 0x6d, 0x69, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x1a, 0x2e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6c, 0x69, 0x62, 0x72,
	0x69, 0x41, 0x64, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x31, 0x5a, 0x2f, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x63, 0x69, 0x6f, 0x6e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x73, 0x63, 0x69, 0x6f, 0x6e, 0x2f, 0x67, 0x6f, 0x2f, 0x70, 0x6b, 0x67, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_daemon_v1_daemon_proto_rawDescOnce sync.Once
	file_proto_daemon_v1_daemon_proto_rawDescData = file_proto_daemon_v1_daemon_proto_rawDesc
)

func file_proto_daemon_v1_daemon_proto_rawDescGZIP() []byte {
	file_proto_daemon_v1_daemon_proto_rawDescOnce.Do(func() {
		file_proto_daemon_v1_daemon_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_daemon_v1_daemon_proto_rawDescData)
	})
	return file_proto_daemon_v1_daemon_proto_rawDescData
}

var file_proto_daemon_v1_daemon_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_daemon_v1_daemon_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_proto_daemon_v1_daemon_proto_goTypes = []interface{}{
	(LinkType)(0),                                // 0: proto.daemon.v1.LinkType
	(*PathsRequest)(nil),                         // 1: proto.daemon.v1.PathsRequest
	(*PathsResponse)(nil),                        // 2: proto.daemon.v1.PathsResponse
	(*Path)(nil),                                 // 3: proto.daemon.v1.Path
	(*PathInterface)(nil),                        // 4: proto.daemon.v1.PathInterface
	(*GeoCoordinates)(nil),                       // 5: proto.daemon.v1.GeoCoordinates
	(*ASRequest)(nil),                            // 6: proto.daemon.v1.ASRequest
	(*ASResponse)(nil),                           // 7: proto.daemon.v1.ASResponse
	(*InterfacesRequest)(nil),                    // 8: proto.daemon.v1.InterfacesRequest
	(*InterfacesResponse)(nil),                   // 9: proto.daemon.v1.InterfacesResponse
	(*Interface)(nil),                            // 10: proto.daemon.v1.Interface
	(*ServicesRequest)(nil),                      // 11: proto.daemon.v1.ServicesRequest
	(*ServicesResponse)(nil),                     // 12: proto.daemon.v1.ServicesResponse
	(*ListService)(nil),                          // 13: proto.daemon.v1.ListService
	(*Service)(nil),                              // 14: proto.daemon.v1.Service
	(*Underlay)(nil),                             // 15: proto.daemon.v1.Underlay
	(*NotifyInterfaceDownRequest)(nil),           // 16: proto.daemon.v1.NotifyInterfaceDownRequest
	(*NotifyInterfaceDownResponse)(nil),          // 17: proto.daemon.v1.NotifyInterfaceDownResponse
	(*DRKeyLvl2Request)(nil),                     // 18: proto.daemon.v1.DRKeyLvl2Request
	(*DRKeyLvl2Response)(nil),                    // 19: proto.daemon.v1.DRKeyLvl2Response
	(*ColibriListRequest)(nil),                   // 20: proto.daemon.v1.ColibriListRequest
	(*ColibriListResponse)(nil),                  // 21: proto.daemon.v1.ColibriListResponse
	(*ColibriSetupRequest)(nil),                  // 22: proto.daemon.v1.ColibriSetupRequest
	(*ColibriSetupResponse)(nil),                 // 23: proto.daemon.v1.ColibriSetupResponse
	(*ColibriCleanupRequest)(nil),                // 24: proto.daemon.v1.ColibriCleanupRequest
	(*ColibriCleanupResponse)(nil),               // 25: proto.daemon.v1.ColibriCleanupResponse
	(*ColibriAdmissionEntry)(nil),                // 26: proto.daemon.v1.ColibriAdmissionEntry
	(*ColibriAdmissionEntryResponse)(nil),        // 27: proto.daemon.v1.ColibriAdmissionEntryResponse
	nil,                                          // 28: proto.daemon.v1.InterfacesResponse.InterfacesEntry
	nil,                                          // 29: proto.daemon.v1.ServicesResponse.ServicesEntry
	(*timestamppb.Timestamp)(nil),                // 30: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),                  // 31: google.protobuf.Duration
	(*drkey.DRKeyLvl2Request)(nil),               // 32: proto.drkey.mgmt.v1.DRKeyLvl2Request
	(*drkey.DRKeyLvl2Response)(nil),              // 33: proto.drkey.mgmt.v1.DRKeyLvl2Response
	(*colibri.ListStitchablesRequest)(nil),       // 34: proto.colibri.v1.ListStitchablesRequest
	(*colibri.ListStitchablesResponse)(nil),      // 35: proto.colibri.v1.ListStitchablesResponse
	(*colibri.DaemonSetupRequest)(nil),           // 36: proto.colibri.v1.DaemonSetupRequest
	(*colibri.DaemonSetupResponse)(nil),          // 37: proto.colibri.v1.DaemonSetupResponse
	(*colibri.DaemonCleanupRequest)(nil),         // 38: proto.colibri.v1.DaemonCleanupRequest
	(*colibri.DaemonCleanupResponse)(nil),        // 39: proto.colibri.v1.DaemonCleanupResponse
	(*colibri.DaemonAdmissionEntry)(nil),         // 40: proto.colibri.v1.DaemonAdmissionEntry
	(*colibri.DaemonAdmissionEntryResponse)(nil), // 41: proto.colibri.v1.DaemonAdmissionEntryResponse
}
var file_proto_daemon_v1_daemon_proto_depIdxs = []int32{
	3,  // 0: proto.daemon.v1.PathsResponse.paths:type_name -> proto.daemon.v1.Path
	10, // 1: proto.daemon.v1.Path.interface:type_name -> proto.daemon.v1.Interface
	4,  // 2: proto.daemon.v1.Path.interfaces:type_name -> proto.daemon.v1.PathInterface
	30, // 3: proto.daemon.v1.Path.expiration:type_name -> google.protobuf.Timestamp
	31, // 4: proto.daemon.v1.Path.latency:type_name -> google.protobuf.Duration
	5,  // 5: proto.daemon.v1.Path.geo:type_name -> proto.daemon.v1.GeoCoordinates
	0,  // 6: proto.daemon.v1.Path.link_type:type_name -> proto.daemon.v1.LinkType
	28, // 7: proto.daemon.v1.InterfacesResponse.interfaces:type_name -> proto.daemon.v1.InterfacesResponse.InterfacesEntry
	15, // 8: proto.daemon.v1.Interface.address:type_name -> proto.daemon.v1.Underlay
	29, // 9: proto.daemon.v1.ServicesResponse.services:type_name -> proto.daemon.v1.ServicesResponse.ServicesEntry
	14, // 10: proto.daemon.v1.ListService.services:type_name -> proto.daemon.v1.Service
	32, // 11: proto.daemon.v1.DRKeyLvl2Request.base_req:type_name -> proto.drkey.mgmt.v1.DRKeyLvl2Request
	33, // 12: proto.daemon.v1.DRKeyLvl2Response.base_rep:type_name -> proto.drkey.mgmt.v1.DRKeyLvl2Response
	34, // 13: proto.daemon.v1.ColibriListRequest.base:type_name -> proto.colibri.v1.ListStitchablesRequest
	35, // 14: proto.daemon.v1.ColibriListResponse.base:type_name -> proto.colibri.v1.ListStitchablesResponse
	36, // 15: proto.daemon.v1.ColibriSetupRequest.base:type_name -> proto.colibri.v1.DaemonSetupRequest
	37, // 16: proto.daemon.v1.ColibriSetupResponse.base:type_name -> proto.colibri.v1.DaemonSetupResponse
	38, // 17: proto.daemon.v1.ColibriCleanupRequest.base:type_name -> proto.colibri.v1.DaemonCleanupRequest
	39, // 18: proto.daemon.v1.ColibriCleanupResponse.base:type_name -> proto.colibri.v1.DaemonCleanupResponse
	40, // 19: proto.daemon.v1.ColibriAdmissionEntry.base:type_name -> proto.colibri.v1.DaemonAdmissionEntry
	41, // 20: proto.daemon.v1.ColibriAdmissionEntryResponse.base:type_name -> proto.colibri.v1.DaemonAdmissionEntryResponse
	10, // 21: proto.daemon.v1.InterfacesResponse.InterfacesEntry.value:type_name -> proto.daemon.v1.Interface
	13, // 22: proto.daemon.v1.ServicesResponse.ServicesEntry.value:type_name -> proto.daemon.v1.ListService
	1,  // 23: proto.daemon.v1.DaemonService.Paths:input_type -> proto.daemon.v1.PathsRequest
	6,  // 24: proto.daemon.v1.DaemonService.AS:input_type -> proto.daemon.v1.ASRequest
	8,  // 25: proto.daemon.v1.DaemonService.Interfaces:input_type -> proto.daemon.v1.InterfacesRequest
	11, // 26: proto.daemon.v1.DaemonService.Services:input_type -> proto.daemon.v1.ServicesRequest
	16, // 27: proto.daemon.v1.DaemonService.NotifyInterfaceDown:input_type -> proto.daemon.v1.NotifyInterfaceDownRequest
	18, // 28: proto.daemon.v1.DaemonService.DRKeyLvl2:input_type -> proto.daemon.v1.DRKeyLvl2Request
	20, // 29: proto.daemon.v1.DaemonService.ColibriListRsvs:input_type -> proto.daemon.v1.ColibriListRequest
	22, // 30: proto.daemon.v1.DaemonService.ColibriSetupRsv:input_type -> proto.daemon.v1.ColibriSetupRequest
	24, // 31: proto.daemon.v1.DaemonService.ColibriCleanupRsv:input_type -> proto.daemon.v1.ColibriCleanupRequest
	26, // 32: proto.daemon.v1.DaemonService.ColibriAddAdmissionEntry:input_type -> proto.daemon.v1.ColibriAdmissionEntry
	2,  // 33: proto.daemon.v1.DaemonService.Paths:output_type -> proto.daemon.v1.PathsResponse
	7,  // 34: proto.daemon.v1.DaemonService.AS:output_type -> proto.daemon.v1.ASResponse
	9,  // 35: proto.daemon.v1.DaemonService.Interfaces:output_type -> proto.daemon.v1.InterfacesResponse
	12, // 36: proto.daemon.v1.DaemonService.Services:output_type -> proto.daemon.v1.ServicesResponse
	17, // 37: proto.daemon.v1.DaemonService.NotifyInterfaceDown:output_type -> proto.daemon.v1.NotifyInterfaceDownResponse
	19, // 38: proto.daemon.v1.DaemonService.DRKeyLvl2:output_type -> proto.daemon.v1.DRKeyLvl2Response
	21, // 39: proto.daemon.v1.DaemonService.ColibriListRsvs:output_type -> proto.daemon.v1.ColibriListResponse
	23, // 40: proto.daemon.v1.DaemonService.ColibriSetupRsv:output_type -> proto.daemon.v1.ColibriSetupResponse
	25, // 41: proto.daemon.v1.DaemonService.ColibriCleanupRsv:output_type -> proto.daemon.v1.ColibriCleanupResponse
	27, // 42: proto.daemon.v1.DaemonService.ColibriAddAdmissionEntry:output_type -> proto.daemon.v1.ColibriAdmissionEntryResponse
	33, // [33:43] is the sub-list for method output_type
	23, // [23:33] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_proto_daemon_v1_daemon_proto_init() }
func file_proto_daemon_v1_daemon_proto_init() {
	if File_proto_daemon_v1_daemon_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_daemon_v1_daemon_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PathsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_daemon_v1_daemon_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PathsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_daemon_v1_daemon_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Path); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_daemon_v1_daemon_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PathInterface); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_daemon_v1_daemon_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GeoCoordinates); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_daemon_v1_daemon_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ASRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_daemon_v1_daemon_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ASResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_daemon_v1_daemon_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InterfacesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_daemon_v1_daemon_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InterfacesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_daemon_v1_daemon_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Interface); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_daemon_v1_daemon_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServicesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_daemon_v1_daemon_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServicesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_daemon_v1_daemon_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListService); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_daemon_v1_daemon_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Service); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_daemon_v1_daemon_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Underlay); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_daemon_v1_daemon_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotifyInterfaceDownRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_daemon_v1_daemon_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotifyInterfaceDownResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_daemon_v1_daemon_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DRKeyLvl2Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_daemon_v1_daemon_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DRKeyLvl2Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_daemon_v1_daemon_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ColibriListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_daemon_v1_daemon_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ColibriListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_daemon_v1_daemon_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ColibriSetupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_daemon_v1_daemon_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ColibriSetupResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_daemon_v1_daemon_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ColibriCleanupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_daemon_v1_daemon_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ColibriCleanupResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_daemon_v1_daemon_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ColibriAdmissionEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_daemon_v1_daemon_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ColibriAdmissionEntryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_daemon_v1_daemon_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_daemon_v1_daemon_proto_goTypes,
		DependencyIndexes: file_proto_daemon_v1_daemon_proto_depIdxs,
		EnumInfos:         file_proto_daemon_v1_daemon_proto_enumTypes,
		MessageInfos:      file_proto_daemon_v1_daemon_proto_msgTypes,
	}.Build()
	File_proto_daemon_v1_daemon_proto = out.File
	file_proto_daemon_v1_daemon_proto_rawDesc = nil
	file_proto_daemon_v1_daemon_proto_goTypes = nil
	file_proto_daemon_v1_daemon_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DaemonServiceClient is the client API for DaemonService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DaemonServiceClient interface {
	Paths(ctx context.Context, in *PathsRequest, opts ...grpc.CallOption) (*PathsResponse, error)
	AS(ctx context.Context, in *ASRequest, opts ...grpc.CallOption) (*ASResponse, error)
	Interfaces(ctx context.Context, in *InterfacesRequest, opts ...grpc.CallOption) (*InterfacesResponse, error)
	Services(ctx context.Context, in *ServicesRequest, opts ...grpc.CallOption) (*ServicesResponse, error)
	NotifyInterfaceDown(ctx context.Context, in *NotifyInterfaceDownRequest, opts ...grpc.CallOption) (*NotifyInterfaceDownResponse, error)
	DRKeyLvl2(ctx context.Context, in *DRKeyLvl2Request, opts ...grpc.CallOption) (*DRKeyLvl2Response, error)
	ColibriListRsvs(ctx context.Context, in *ColibriListRequest, opts ...grpc.CallOption) (*ColibriListResponse, error)
	ColibriSetupRsv(ctx context.Context, in *ColibriSetupRequest, opts ...grpc.CallOption) (*ColibriSetupResponse, error)
	ColibriCleanupRsv(ctx context.Context, in *ColibriCleanupRequest, opts ...grpc.CallOption) (*ColibriCleanupResponse, error)
	ColibriAddAdmissionEntry(ctx context.Context, in *ColibriAdmissionEntry, opts ...grpc.CallOption) (*ColibriAdmissionEntryResponse, error)
}

type daemonServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDaemonServiceClient(cc grpc.ClientConnInterface) DaemonServiceClient {
	return &daemonServiceClient{cc}
}

func (c *daemonServiceClient) Paths(ctx context.Context, in *PathsRequest, opts ...grpc.CallOption) (*PathsResponse, error) {
	out := new(PathsResponse)
	err := c.cc.Invoke(ctx, "/proto.daemon.v1.DaemonService/Paths", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) AS(ctx context.Context, in *ASRequest, opts ...grpc.CallOption) (*ASResponse, error) {
	out := new(ASResponse)
	err := c.cc.Invoke(ctx, "/proto.daemon.v1.DaemonService/AS", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) Interfaces(ctx context.Context, in *InterfacesRequest, opts ...grpc.CallOption) (*InterfacesResponse, error) {
	out := new(InterfacesResponse)
	err := c.cc.Invoke(ctx, "/proto.daemon.v1.DaemonService/Interfaces", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) Services(ctx context.Context, in *ServicesRequest, opts ...grpc.CallOption) (*ServicesResponse, error) {
	out := new(ServicesResponse)
	err := c.cc.Invoke(ctx, "/proto.daemon.v1.DaemonService/Services", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) NotifyInterfaceDown(ctx context.Context, in *NotifyInterfaceDownRequest, opts ...grpc.CallOption) (*NotifyInterfaceDownResponse, error) {
	out := new(NotifyInterfaceDownResponse)
	err := c.cc.Invoke(ctx, "/proto.daemon.v1.DaemonService/NotifyInterfaceDown", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) DRKeyLvl2(ctx context.Context, in *DRKeyLvl2Request, opts ...grpc.CallOption) (*DRKeyLvl2Response, error) {
	out := new(DRKeyLvl2Response)
	err := c.cc.Invoke(ctx, "/proto.daemon.v1.DaemonService/DRKeyLvl2", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) ColibriListRsvs(ctx context.Context, in *ColibriListRequest, opts ...grpc.CallOption) (*ColibriListResponse, error) {
	out := new(ColibriListResponse)
	err := c.cc.Invoke(ctx, "/proto.daemon.v1.DaemonService/ColibriListRsvs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) ColibriSetupRsv(ctx context.Context, in *ColibriSetupRequest, opts ...grpc.CallOption) (*ColibriSetupResponse, error) {
	out := new(ColibriSetupResponse)
	err := c.cc.Invoke(ctx, "/proto.daemon.v1.DaemonService/ColibriSetupRsv", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) ColibriCleanupRsv(ctx context.Context, in *ColibriCleanupRequest, opts ...grpc.CallOption) (*ColibriCleanupResponse, error) {
	out := new(ColibriCleanupResponse)
	err := c.cc.Invoke(ctx, "/proto.daemon.v1.DaemonService/ColibriCleanupRsv", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) ColibriAddAdmissionEntry(ctx context.Context, in *ColibriAdmissionEntry, opts ...grpc.CallOption) (*ColibriAdmissionEntryResponse, error) {
	out := new(ColibriAdmissionEntryResponse)
	err := c.cc.Invoke(ctx, "/proto.daemon.v1.DaemonService/ColibriAddAdmissionEntry", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DaemonServiceServer is the server API for DaemonService service.
type DaemonServiceServer interface {
	Paths(context.Context, *PathsRequest) (*PathsResponse, error)
	AS(context.Context, *ASRequest) (*ASResponse, error)
	Interfaces(context.Context, *InterfacesRequest) (*InterfacesResponse, error)
	Services(context.Context, *ServicesRequest) (*ServicesResponse, error)
	NotifyInterfaceDown(context.Context, *NotifyInterfaceDownRequest) (*NotifyInterfaceDownResponse, error)
	DRKeyLvl2(context.Context, *DRKeyLvl2Request) (*DRKeyLvl2Response, error)
	ColibriListRsvs(context.Context, *ColibriListRequest) (*ColibriListResponse, error)
	ColibriSetupRsv(context.Context, *ColibriSetupRequest) (*ColibriSetupResponse, error)
	ColibriCleanupRsv(context.Context, *ColibriCleanupRequest) (*ColibriCleanupResponse, error)
	ColibriAddAdmissionEntry(context.Context, *ColibriAdmissionEntry) (*ColibriAdmissionEntryResponse, error)
}

// UnimplementedDaemonServiceServer can be embedded to have forward compatible implementations.
type UnimplementedDaemonServiceServer struct {
}

func (*UnimplementedDaemonServiceServer) Paths(context.Context, *PathsRequest) (*PathsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Paths not implemented")
}
func (*UnimplementedDaemonServiceServer) AS(context.Context, *ASRequest) (*ASResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AS not implemented")
}
func (*UnimplementedDaemonServiceServer) Interfaces(context.Context, *InterfacesRequest) (*InterfacesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Interfaces not implemented")
}
func (*UnimplementedDaemonServiceServer) Services(context.Context, *ServicesRequest) (*ServicesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Services not implemented")
}
func (*UnimplementedDaemonServiceServer) NotifyInterfaceDown(context.Context, *NotifyInterfaceDownRequest) (*NotifyInterfaceDownResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NotifyInterfaceDown not implemented")
}
func (*UnimplementedDaemonServiceServer) DRKeyLvl2(context.Context, *DRKeyLvl2Request) (*DRKeyLvl2Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DRKeyLvl2 not implemented")
}
func (*UnimplementedDaemonServiceServer) ColibriListRsvs(context.Context, *ColibriListRequest) (*ColibriListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ColibriListRsvs not implemented")
}
func (*UnimplementedDaemonServiceServer) ColibriSetupRsv(context.Context, *ColibriSetupRequest) (*ColibriSetupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ColibriSetupRsv not implemented")
}
func (*UnimplementedDaemonServiceServer) ColibriCleanupRsv(context.Context, *ColibriCleanupRequest) (*ColibriCleanupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ColibriCleanupRsv not implemented")
}
func (*UnimplementedDaemonServiceServer) ColibriAddAdmissionEntry(context.Context, *ColibriAdmissionEntry) (*ColibriAdmissionEntryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ColibriAddAdmissionEntry not implemented")
}

func RegisterDaemonServiceServer(s *grpc.Server, srv DaemonServiceServer) {
	s.RegisterService(&_DaemonService_serviceDesc, srv)
}

func _DaemonService_Paths_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PathsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).Paths(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.daemon.v1.DaemonService/Paths",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).Paths(ctx, req.(*PathsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_AS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ASRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).AS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.daemon.v1.DaemonService/AS",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).AS(ctx, req.(*ASRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_Interfaces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InterfacesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).Interfaces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.daemon.v1.DaemonService/Interfaces",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).Interfaces(ctx, req.(*InterfacesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_Services_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).Services(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.daemon.v1.DaemonService/Services",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).Services(ctx, req.(*ServicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_NotifyInterfaceDown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyInterfaceDownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).NotifyInterfaceDown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.daemon.v1.DaemonService/NotifyInterfaceDown",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).NotifyInterfaceDown(ctx, req.(*NotifyInterfaceDownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_DRKeyLvl2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DRKeyLvl2Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).DRKeyLvl2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.daemon.v1.DaemonService/DRKeyLvl2",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).DRKeyLvl2(ctx, req.(*DRKeyLvl2Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_ColibriListRsvs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ColibriListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).ColibriListRsvs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.daemon.v1.DaemonService/ColibriListRsvs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).ColibriListRsvs(ctx, req.(*ColibriListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_ColibriSetupRsv_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ColibriSetupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).ColibriSetupRsv(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.daemon.v1.DaemonService/ColibriSetupRsv",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).ColibriSetupRsv(ctx, req.(*ColibriSetupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_ColibriCleanupRsv_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ColibriCleanupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).ColibriCleanupRsv(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.daemon.v1.DaemonService/ColibriCleanupRsv",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).ColibriCleanupRsv(ctx, req.(*ColibriCleanupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_ColibriAddAdmissionEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ColibriAdmissionEntry)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).ColibriAddAdmissionEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.daemon.v1.DaemonService/ColibriAddAdmissionEntry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).ColibriAddAdmissionEntry(ctx, req.(*ColibriAdmissionEntry))
	}
	return interceptor(ctx, in, info, handler)
}

var _DaemonService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.daemon.v1.DaemonService",
	HandlerType: (*DaemonServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Paths",
			Handler:    _DaemonService_Paths_Handler,
		},
		{
			MethodName: "AS",
			Handler:    _DaemonService_AS_Handler,
		},
		{
			MethodName: "Interfaces",
			Handler:    _DaemonService_Interfaces_Handler,
		},
		{
			MethodName: "Services",
			Handler:    _DaemonService_Services_Handler,
		},
		{
			MethodName: "NotifyInterfaceDown",
			Handler:    _DaemonService_NotifyInterfaceDown_Handler,
		},
		{
			MethodName: "DRKeyLvl2",
			Handler:    _DaemonService_DRKeyLvl2_Handler,
		},
		{
			MethodName: "ColibriListRsvs",
			Handler:    _DaemonService_ColibriListRsvs_Handler,
		},
		{
			MethodName: "ColibriSetupRsv",
			Handler:    _DaemonService_ColibriSetupRsv_Handler,
		},
		{
			MethodName: "ColibriCleanupRsv",
			Handler:    _DaemonService_ColibriCleanupRsv_Handler,
		},
		{
			MethodName: "ColibriAddAdmissionEntry",
			Handler:    _DaemonService_ColibriAddAdmissionEntry_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/daemon/v1/daemon.proto",
}
