// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/scionproto/scion/go/pkg/cs/drkey (interfaces: Fetcher)

// Package mock_drkey is a generated GoMock package.
package mock_drkey

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	addr "github.com/scionproto/scion/go/lib/addr"
	drkey "github.com/scionproto/scion/go/lib/drkey"
	reflect "reflect"
	time "time"
)

// MockFetcher is a mock of Fetcher interface
type MockFetcher struct {
	ctrl     *gomock.Controller
	recorder *MockFetcherMockRecorder
}

// MockFetcherMockRecorder is the mock recorder for MockFetcher
type MockFetcherMockRecorder struct {
	mock *MockFetcher
}

// NewMockFetcher creates a new mock instance
func NewMockFetcher(ctrl *gomock.Controller) *MockFetcher {
	mock := &MockFetcher{ctrl: ctrl}
	mock.recorder = &MockFetcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockFetcher) EXPECT() *MockFetcherMockRecorder {
	return m.recorder
}

// GetLvl1FromOtherCS mocks base method
func (m *MockFetcher) GetLvl1FromOtherCS(arg0 context.Context, arg1, arg2 addr.IA, arg3 time.Time) (drkey.Lvl1Key, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLvl1FromOtherCS", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(drkey.Lvl1Key)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLvl1FromOtherCS indicates an expected call of GetLvl1FromOtherCS
func (mr *MockFetcherMockRecorder) GetLvl1FromOtherCS(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLvl1FromOtherCS", reflect.TypeOf((*MockFetcher)(nil).GetLvl1FromOtherCS), arg0, arg1, arg2, arg3)
}
